# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media
resources:
  - audiobookshelf/ks.yaml
  - bazarr/ks.yaml
  - booklore/ks.yaml
  - jellyfin/ks.yaml
  - maintainerr/ks.yaml
  - plex/ks.yaml
  - prowlarr/ks.yaml
  - qbittorrent/ks.yaml
  - radarr/ks.yaml
  - recyclarr/ks.yaml
  - sabnzbd/ks.yaml
  - seerr/ks.yaml
  - shelfmark/ks.yaml
  - sonarr/ks.yaml
  - tautulli/ks.yaml
  - volume/ks.yaml
components:
  - ../../components/namespace
