[env]
KUBECONFIG = "{{config_root}}/kubeconfig"
TALOSCONFIG = "{{config_root}}/talosconfig"
JUST_UNSTABLE = 1
MINIJINJA_CONFIG_FILE = "{{config_root}}/.minijinja.toml"

[tools]
ansible = "latest"
flux2 = "latest"
helmfile = "latest"
kubectl = "latest"
"pipx:flux-local" = "latest"
sops = "latest"
talosctl = "latest"
task = "latest"
uv = "latest"
yq = "latest"
k9s = "latest"
just = "latest"
"ubi:mitsuhiko/minijinja" = "latest"
gum = "latest"
1password = "latest"
