# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app kopia
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: *app

  values:
    controllers:
      kopia-nas:
        annotations:
          reloader.stakater.com/auto: "true"

        containers:
          app:
            image:
              repository: ghcr.io/home-operations/kopia
              tag: 0.22.0@sha256:aa6a2f5987b9c991a349c34e0c7ef80f00366d84490d7637355b10d38fcbc034

            args:
              - --without-password

            env:
              TZ: Europe/Berlin
              KOPIA_WEB_ENABLED: true
              KOPIA_WEB_PORT: &port 8080
              KOPIA_PASSWORD:
                valueFrom:
                  secretKeyRef:
                    name: kopia
                    key: repo_key

            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: *port
              readiness: *probes
              startup: *probes

            resources:
              requests:
                cpu: 15m
                memory: 50Mi
              limits:
                memory: 500Gi

            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL

      kopia-cloud:
        annotations:
          reloader.stakater.com/auto: "true"

        containers:
          app:
            image:
              repository: ghcr.io/home-operations/kopia
              tag: 0.22.0@sha256:aa6a2f5987b9c991a349c34e0c7ef80f00366d84490d7637355b10d38fcbc034

            args:
              - --without-password

            env:
              TZ: Europe/Berlin
              KOPIA_WEB_ENABLED: true
              KOPIA_WEB_PORT: *port
              KOPIA_PASSWORD:
                valueFrom:
                  secretKeyRef:
                    name: kopia
                    key: repo_key

            probes:
              liveness: *probes
              readiness: *probes
              startup: *probes

            resources:
              requests:
                cpu: 15m
                memory: 50Mi
              limits:
                memory: 500Gi

            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL

    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 2000
        runAsGroup: 2000
        fsGroup: 2000
        fsGroupChangePolicy: OnRootMismatch

    service:
      nas:
        controller: kopia-nas
        ports:
          http:
            port: *port
      cloud:
        controller: kopia-cloud
        ports:
          http:
            port: *port

    ingress:
      app:
        className: internal
        annotations:
          nginx.ingress.kubernetes.io/auth-url: http://authelia.auth.svc.cluster.local/api/authz/auth-request
          nginx.ingress.kubernetes.io/auth-signin: https://auth.${domain}?rm=$request_method
          nginx.ingress.kubernetes.io/auth-response-headers: Remote-User,Remote-Name,Remote-Groups,Remote-Email
        hosts:
          - host: kopia-nas.${domain}
            paths:
              - path: /
                service:
                  identifier: nas
                  port: http
          - host: kopia-cloud.${domain}
            paths:
              - path: /
                service:
                  identifier: cloud
                  port: http

    persistence:
      config-file:
        type: secret
        name: kopia
        advancedMounts:
          kopia-nas:
            app:
              - path: /config/repository.config
                subPath: repository.config.nas
                readOnly: true
          kopia-cloud:
            app:
              - path: /config/repository.config
                subPath: repository.config.cloud
                readOnly: true

      tmp:
        type: emptyDir
        advancedMounts:
          kopia-nas:
            app:
              - path: /config/cache
                subPath: cache/nas
              - path: /config/logs
                subPath: logs/nas
              - path: /tmp
                subPath: tmp/nas
          kopia-cloud:
            app:
              - path: /config/cache
                subPath: cache/cloud
              - path: /config/logs
                subPath: logs/cloud
              - path: /tmp
                subPath: tmp/cloud
