apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ${volsync_claim:=${app}}
  labels:
    app.kubernetes.io/name: ${app}
spec:
  accessModes:
    - ${volsync_accessmodes:=ReadWriteOnce}
  dataSourceRef:
    kind: ReplicationDestination
    apiGroup: volsync.backube
    name: ${app}
  resources:
    requests:
      storage: ${volsync_capacity:=1Gi}
  storageClassName: ${volsync_storageclass:=longhorn}
