# yaml-language-server: $schema=https://schemaz.pages.dev/volsync.backube/replicationsource_v1alpha1.json
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: ${app}
spec:
  sourcePVC: ${volsync_claim:=${app}}
  trigger:
    schedule: "0 * * * *"
  kopia:
    repository: ${app}-volsync
    copyMethod: ${volsync_copymethod:=Clone}
    storageClassName: ${volsync_storageclass:=longhorn-tmp}
    volumeSnapshotClassName: ${volsync_snapshotclass:=longhorn}
    accessModes:
      - ${volsync_accessmodes:=ReadWriteOnce}
    moverSecurityContext:
      runAsUser: ${volsync_puid:=2000}
      runAsGroup: ${volsync_pgid:=2000}
      fsGroup: ${volsync_pgid:=2000}
    retain:
      hourly: 24
      daily: 7
      weekly: 4
    parallelism: 2
    compression: zstd-fastest
