# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: hosted
resources:
  - booklore/ks.yaml
  - changedetection/ks.yaml
  - shlink/ks.yaml
  - silverbullet/ks.yaml
  - vikunja/ks.yaml
components:
  - ../../components/namespace
