# yaml-language-server: $schema=https://schemaz.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: cilium
spec:
  url: oci://quay.io/cilium/charts/cilium
  ref:
    tag: 1.19.0
  interval: 10m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
