# yaml-language-server: $schema=https://schemaz.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: booklore
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: cpgo
  target:
    template:
      data:
        DATABASE_URL: '{{ index . "pgbouncer-jdbc-uri" }}'
        DATABASE_USERNAME: "{{ .user }}"
        DATABASE_PASSWORD: "{{ .password }}"
  dataFrom:
    - extract:
        key: postgres-pguser-booklore
