# yaml-language-server: $schema=https://schemaz.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: crunchy-userinit-controller
spec:
  interval: 30m
  chart:
    spec:
      chart: crunchy-userinit-controller
      version: 1.0.3
      sourceRef:
        kind: HelmRepository
        name: crunchy-userinit-controller
