# yaml-language-server: $schema=https://schemaz.pages.dev/source.toolkit.fluxcd.io/helmrepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: crunchy-userinit-controller
spec:
  url: https://drummyfloyd.github.io/crunchy-userinit-controller
  interval: 30m
