# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: automation
resources:
  - esphome/ks.yaml
  - home-assistant/ks.yaml
  - n8n/ks.yaml
  - node-red/ks.yaml
  - windmill/ks.yaml
  - zigbee2mqtt/ks.yaml
components:
  - ../../components/namespace
